FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHOUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "manage,py", "runserver" ,"0.0.0.0:8000"]