# Generated by Django 6.0.5 on 2026-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cryptoprice',
            new_name='crypto_app__symbol_869981_idx',
            old_name='app_1_crypt_symbol_7db764_idx',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
